name: reviewdog

on: pull_request

jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: misspell
        uses: HENNGE/action-misspell@v1.9.1.rc
        with:
          exclude: |
            *.ignore
